apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pool-ssd-set2
  namespace: rook-ceph 
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  deviceClass: ssd-set2
  parameters:
    compression_mode: none
  mirroring:
    enabled: false
    mode: image
  statusCheck:
    mirror:
      disabled: false
      interval: 60s
