---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-rwx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
  volumeMode: Block
