apiVersion: v1
kind: Namespace
metadata:
  name: tenant-certmanager
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: tenant-certmanager
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: Y29uc29sZQ==
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw==
kind: Secret
metadata:
  name: storage-user
  namespace: tenant-certmanager
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: tenant-certmanager
spec:
  dnsNames:
  - '*.tenant-certmanager.svc.cluster.local'
  - '*.storage-certmanager.tenant-certmanager.svc.cluster.local'
  - '*.storage-certmanager-hl.tenant-certmanager.svc.cluster.local'
  issuerRef:
    name: tenant-certmanager-issuer
  secretName: tenant-certmanager-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tenant-certmanager-issuer
  namespace: tenant-certmanager
spec:
  selfSigned: {}
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: storage-certmanager
  namespace: tenant-certmanager
spec:
  exposeServices:
    console: true
  certConfig: {}
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret:
  - name: tenant-certmanager-tls
    type: cert-manager.io/v1
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: minio/minio:RELEASE.2022-11-11T03-44-20Z
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: pool-0
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
    servers: 2
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "5368709120"
        storageClassName: direct-csi-min-io
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    volumesPerServer: 4
  requestAutoCert: false
